version: '3.8'

services:
  # Serwis bazy danych PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: vr_postgres_db
    restart: always
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: super_tajne_haslo123
      POSTGRES_DB: kosmos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # MONITORING BAZY: Docker sprawdza czy baza odpowiada na komendę pg_isready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U student -d kosmos_db"]
      interval: 10s
      timeout: 5s
      retries: 5

# Serwis naszego backendu w Node.js
  backend:
    build: ./backend
    container_name: vr_node_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # <-- TA LINIA DAJE DOSTĘP DO STATUSU DOCKERA
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      
volumes:
  postgres_data: